apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: calculator
  namespace: calculator
spec:
  dnsNames:
    - calculator.grid.demanddriventech.com
  secretName: calculator-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer